version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
       - python3 test.py
  build:
    commands:
       - ls -la
       - zip ${LAMBDA_CODE_ZIP_FILE_NAME} test.py
  post_build:
    commands:
       - aws lambda update-function-code --function-name  ${LAMBDA_FUNCTION_NAME} --zip-file fileb://${LAMBDA_CODE_ZIP_FILE_NAME} --region ${LAMBDA_REGION}
